version: '3.7'

services:
  api:
    build: ./api
    container_name: restfulapi
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app

  jupyter:
    build: ./jupyter
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/home/jovyan
      - ./api:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes