version: '3.8'

services:
  api:
    build: ./app
    container_name: flask-restful-api
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./model:/model

  jupyter:
    build: ./notebooks
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
      - ./model:/model
    environment:
      - JUPYTER_ENABLE_LAB=yes